name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  SOLUTION_FILE: code/Infiniminer.sln
  DOTNET_VERSION: '8.0.x'
  MONOGAME_VERSION: '3.8.2.1105'

jobs:
  # First job: Build and package everything (Windows can cross-compile)
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Update Version
      if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      run: |
        $version = "${{ github.ref_name }}"
        $file = "code/InfiniminerShared/SharedConstants.cs"
        $content = Get-Content $file
        $content = $content -replace 'INFINIMINER_VERSION = ".*?"', "INFINIMINER_VERSION = `"$version Infinifortress`""
        Set-Content $file $content

    - name: Install MGCB
      run: |
        dotnet tool install -g dotnet-mgcb
        dotnet tool install -g dotnet-mgcb-editor
        dotnet tool restore

    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build Content
      shell: pwsh
      run: |
        cd code/InfiniminerClient/Content
        mgcb Content.mgcb /platform:DesktopGL

    - name: Build All Platforms
      shell: pwsh
      run: |
        $rids = @('win-x64', 'linux-x64', 'osx-x64')
        foreach ($rid in $rids) {
          # Build Client
          dotnet publish code/InfiniminerClient/InfiniminerClient.csproj `
            -c Release `
            -r $rid `
            --self-contained true `
            -p:PublishSingleFile=true `
            -o "publish/Infinifortress-$rid-Client"

          # Build Server  
          dotnet publish code/InfiniminerServer/InfiniminerServer.csproj `
            -c Release `
            -r $rid `
            --self-contained true `
            -p:PublishSingleFile=true `
            -o "publish/Infinifortress-$rid-Server"

          # Package builds
          Compress-Archive `
            -Path "publish/Infinifortress-$rid-Client/*" `
            -DestinationPath "Infinifortress-$rid-Client.zip" -Force

          Compress-Archive `
            -Path "publish/Infinifortress-$rid-Server/*" `
            -DestinationPath "Infinifortress-$rid-Server.zip" -Force
        }

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Infinifortress-Builds
        path: |
          Infinifortress-*-Client.zip
          Infinifortress-*-Server.zip
        retention-days: 5

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: Infinifortress ${{ github.ref_name }}
        files: |
          Infinifortress-*-Client.zip
          Infinifortress-*-Server.zip
        body: |
          Release ${{ github.ref_name }}
          
          This release includes:
          
          Windows:
          - Infinifortress-win-x64-Client.zip
          - Infinifortress-win-x64-Server.zip
          
          Linux:
          - Infinifortress-linux-x64-Client.zip
          - Infinifortress-linux-x64-Server.zip
          
          macOS:
          - Infinifortress-osx-x64-Client.zip
          - Infinifortress-osx-x64-Server.zip 