name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  SOLUTION_FILE: code/Infiniminer.sln
  DOTNET_VERSION: '8.0.x'
  MONOGAME_VERSION: '3.8.2.1105'

jobs:
  # First job: Verify the build works (for PRs and pushes)
  verify:
    runs-on: windows-latest # MonoGame content build works best on Windows
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MGCB
      run: |
        dotnet tool install -g dotnet-mgcb --version ${{ env.MONOGAME_VERSION }}
        dotnet tool install -g dotnet-mgcb-editor --version ${{ env.MONOGAME_VERSION }}
        dotnet tool restore

    - name: Create MGCB Config
      shell: pwsh
      run: |
        $configPath = "$env:USERPROFILE/.mgcb"
        New-Item -ItemType Directory -Force -Path (Split-Path $configPath)
        @"
        /platform:Windows
        /profile:HiDef
        /compress:False
        /config:
        /reference:
        "@ | Set-Content $configPath

    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build Content
      shell: pwsh
      run: |
        cd code/InfiniminerClient/Content
        mgcb Content.mgcb /platform:Windows

    - name: Build Solution
      run: dotnet build ${{ env.SOLUTION_FILE }} -c Release --no-restore

  # Second job: Build releases for all platforms (only on tags)
  release-build:
    needs: verify
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        config:
          - os: windows-latest
            platform: Windows
            rid: win-x64
          - os: ubuntu-latest
            platform: Linux 
            rid: linux-x64
          - os: macos-latest
            platform: MacOS
            rid: osx-x64
    
    runs-on: ${{ matrix.config.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Update Version
      shell: pwsh
      run: |
        $version = "${{ github.ref_name }}"
        $file = "code/InfiniminerShared/SharedConstants.cs"
        $content = Get-Content $file
        $content = $content -replace 'INFINIMINER_VERSION = ".*?"', "INFINIMINER_VERSION = `"$version Infinifortress`""
        Set-Content $file $content

    - name: Install MGCB
      run: |
        dotnet tool install -g dotnet-mgcb --version ${{ env.MONOGAME_VERSION }}
        dotnet tool install -g dotnet-mgcb-editor --version ${{ env.MONOGAME_VERSION }}
        dotnet tool restore

    - name: Create MGCB Config
      shell: pwsh
      run: |
        $configPath = if ($IsWindows) { "$env:USERPROFILE/.mgcb" } else { "$env:HOME/.mgcb" }
        New-Item -ItemType Directory -Force -Path (Split-Path $configPath)
        @"
        /platform:${{ matrix.config.platform }}
        /profile:HiDef
        /compress:False
        /config:
        /reference:
        "@ | Set-Content $configPath

    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build Content
      shell: pwsh
      run: |
        cd code/InfiniminerClient/Content
        mgcb Content.mgcb /platform:${{ matrix.config.platform }}

    - name: Build Client
      shell: pwsh
      run: |
        dotnet publish code/InfiniminerClient/InfiniminerClient.csproj `
          -c Release `
          -r ${{ matrix.config.rid }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -o "publish/Infinifortress2-${{ matrix.config.platform }}-Client"

    - name: Build Server
      shell: pwsh
      run: |
        dotnet publish code/InfiniminerServer/InfiniminerServer.csproj `
          -c Release `
          -r ${{ matrix.config.rid }} `
          --self-contained true `
          -p:PublishSingleFile=true `
          -o "publish/Infinifortress2-${{ matrix.config.platform }}-Server"

    - name: Package Builds
      shell: pwsh
      run: |
        # Package client
        Compress-Archive `
          -Path "publish/Infinifortress2-${{ matrix.config.platform }}-Client/*" `
          -DestinationPath "Infinifortress2-${{ matrix.config.platform }}-Client.zip"
        
        # Package server
        Compress-Archive `
          -Path "publish/Infinifortress2-${{ matrix.config.platform }}-Server/*" `
          -DestinationPath "Infinifortress2-${{ matrix.config.platform }}-Server.zip"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Infinifortress2-${{ matrix.config.platform }}
        path: |
          Infinifortress2-${{ matrix.config.platform }}-Client.zip
          Infinifortress2-${{ matrix.config.platform }}-Server.zip
        retention-days: 5

  # Third job: Create the actual release (only on tags)
  create-release:
    needs: release-build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Infinifortress2 ${{ github.ref_name }}
          files: |
            */Infinifortress2-*-Client.zip
            */Infinifortress2-*-Server.zip
          body: |
            Release ${{ github.ref_name }}
            
            This release includes:
            
            Windows:
            - Infinifortress2-Windows-Client.zip
            - Infinifortress2-Windows-Server.zip
            
            Linux:
            - Infinifortress2-Linux-Client.zip
            - Infinifortress2-Linux-Server.zip
            
            macOS:
            - Infinifortress2-MacOS-Client.zip
            - Infinifortress2-MacOS-Server.zip 